# Generated by Django 5.2.14 on 2026-05-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer', '0001_initial'),
        ('pretix_enablebanking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableBankingImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enablebankingaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enablebankingconnection',
            name='auth_state',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='enablebankingaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enablebankingconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='enablebankingaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'account_uid'), name='enablebanking_account_unique_uid_per_connection'),
        ),
        migrations.AddField(
            model_name='enablebankingimportjob',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='pretix_enablebanking.enablebankingaccount'),
        ),
        migrations.AddField(
            model_name='enablebankingimportjob',
            name='bank_import_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enablebanking_source', to='banktransfer.bankimportjob'),
        ),
        migrations.AddField(
            model_name='enablebankingimportjob',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablebanking_import_jobs', to='pretixbase.organizer'),
        ),
    ]
