# Generated by Django 5.2.14 on 2026-05-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer', '0012_org_level_plugin'),
        ('pretix_enablebanking', '0001_initial'),
        ('pretixbase', '0300_alter_customer_locale_alter_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enablebankingaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enablebankingconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EnableBankingImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='pretix_enablebanking.enablebankingaccount')),
                ('bank_import_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enablebanking_source', to='banktransfer.bankimportjob')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablebanking_import_jobs', to='pretixbase.organizer')),
            ],
        ),
    ]
