# Generated by Django 5.2.14 on 2026-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_enablebanking', '0002_enablebankingimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='enablebankingconnection',
            name='auth_state',
            field=models.CharField(default='', max_length=64),
        ),
    ]
