# Generated by Django 5.2.14 on 2026-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_enablebanking', '0003_enablebankingconnection_auth_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enablebankingaccount',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enablebankingaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'account_uid'), name='enablebanking_account_unique_uid_per_connection'),
        ),
    ]
